### ISSUE TITLE
How to set enrich context

### ISSUE THREAD

**Issue by arisliang** [serilogj/serilogj#13]
In LoggerConfiguration class, there is a "with" method to enrich logs. I don't see it in the usage example. How to use it?

**Comment by nblumhardt** [comment]
Hi Aris - this largely depends on what kind of enrichment you want to apply. Calling `Enrich.WithProperty()` on the `LoggerConfiguration` will add a static property value, for example.

https://github.com/serilog/serilog-enrichers-thread implements an `ILogEventEnricher` for attaching thread ids to events, this is probably a pretty good example codebase to check out for more details.

HTH!

**Comment by gmyrianthous** [comment]
> Hi Aris - this largely depends on what kind of enrichment you want to apply. Calling `Enrich.WithProperty()` on the `LoggerConfiguration` will add a static property value, for example.
> 
> https://github.com/serilog/serilog-enrichers-thread implements an `ILogEventEnricher` for attaching thread ids to events, this is probably a pretty good example codebase to check out for more details.
> 
> HTH!

Hi, 

 ```
       Log.setLogger(new LoggerConfiguration()
                .Enrich.WithProperty("Environemnt", "Development")
                .writeTo(seq("http://localhost:6060/"))
                .setMinimumLevel(LogEventLevel.Verbose)
                .createLogger());  
```

 doesn't seem to be working for Java though. 
Can you please shed some light here?

**Comment by nblumhardt** [comment]
I'm sorry @aris and @gmyrianthous - I didn't notice when replying to the original post that this is in the `serilogj` repository and not the .NET `serilog` repository. It looks like `withProperty` and some of the other enrichment configuration is missing and/or different in this codebase.

Something like the following should do it:

```java
   // import serilogj.events.*;
   // import serilogj.core.enrichers.*;
   .with(new FixedPropertyEnricher(new LogEventProperty("Environment", new ScalarValue("Development")))
```

HTH!

**Comment by gmyrianthous** [comment]
> I'm sorry @aris and @gmyrianthous - I didn't notice when replying to the original post that this is in the `serilogj` repository and not the .NET `serilog` repository. It looks like `withProperty` and some of the other enrichment configuration is missing and/or different in this codebase.
> 
> Something like the following should do it:
> 
> ```java
>    // import serilogj.events.*;
>    // import serilogj.core.enrichers.*;
>    .with(new FixedPropertyEnricher(new LogEventProperty("Environment", new ScalarValue("Development")))
> ```
> 
> HTH!

Cheers! This does work (You've missed a parenthesis at the end though )

**Comment by nblumhardt** [comment]
Great, thanks for the follow-up 👍
