### ISSUE TITLE
The Maven dependency doesn't download the Jar file

### ISSUE THREAD

**Issue by deven83** [serilogj/serilogj#14]
Used the documentation to add serilogj as a Maven dependency using the following pom file.
```
<repositories>
         <repository>
             <snapshots>
                 <enabled>true</enabled>
             </snapshots>
             <id>bintray-serilogj-serilogj</id>
             <name>bintray</name>
             <url>https://dl.bintray.com/serilogj/serilogj</url>
         </repository>
     </repositories>
     <pluginRepositories>
         <pluginRepository>
             <snapshots>
                 <enabled>false</enabled>
             </snapshots>
             <id>bintray-serilogj-serilogj</id>
             <name>bintray-plugins</name>
             <url>https://dl.bintray.com/serilogj/serilogj</url>
         </pluginRepository>
     </pluginRepositories>
         <dependencies>
		<dependency>
		  <groupId>org.serilogj.serilogj</groupId>
		  <artifactId>serilogj</artifactId>
		  <version>0.5.1</version>
		  <type>pom</type>
		</dependency>
	</dependencies>
```

However this doesn't download the Serilogj Jar file in the maven dependencies folder. Could it be a permission issue on bintray?

**Comment by nblumhardt** [comment]
Hi @deven83  - I'm not familiar enough with Maven to be much help here, but there doesn't seem to be an issue with accessing the JARs directly (e.g. see https://dl.bintray.com/serilogj/serilogj/org/serilogj/serilogj/serilogj/0.5.1/). HTH...

**Comment by Mart-Bogdan** [comment]
@deven83 let's publish XML snippets without indention in 2018.

modern technologies.

**Comment by nblumhardt** [comment]
Formatting fixed, just needed the triple-backtick fence <code>```</code>. Not everyone's spent a lot of time on GitHub, let's keep the issue tracker friendly :-)

**Comment by deven83** [comment]
Most likely it looks like a corrupt workspace in eclipse. When I started from scratch again, it worked out fine.

Sorry for the false alarm.
