### ISSUE TITLE
Could you push this to an official maven repo?

### ISSUE THREAD

**Issue by mjnorman** [serilogj/serilogj#15]
That way we could pull it in dynamically via dependency.  Thanks!

**Comment by nblumhardt** [comment]
Hi! Is the [bintray](https://bintray.com/serilogj/serilogj/serilogj) deployment adequate for this? Thanks!

**Comment by mjnorman** [comment]
Worked like a champ.  However in case anyone runs across, I used the following.  (Excluded the <type>pom</type> tag which bintray suggests to use.

```	    <repository>
	      <id>bintray-serilogj-maven</id>
	      <name>bintray.com</name>
	      <url>https://dl.bintray.com/serilogj/serilogj/</url>
	    </repository>
	  </repositories>
...
		<dependency>
		  <groupId>org.serilogj.serilogj</groupId>
		  <artifactId>serilogj</artifactId>
		  <version>0.5.1</version>
		</dependency>
```
