### ISSUE TITLE
Sample configuration does not work as written

### ISSUE THREAD

**Issue by mjnorman** [serilogj/serilogj#20]
According to the documentation here and on getseq, it shows that we should be able to do the following:

```Log.setLogger(new LoggerConfiguration()
    .writeTo(seq("http://localhost:5341"))
    .createLogger());
```

However there is no method `seq(<string>)`, so this generates an error.

I have been able to work around this in the past by doing 

```
SeqSink mysink = new SeqSink("server", "key", null, Duration.ofSeconds(2), null, levelswitch);
```

although not sure this is the proper way to do it.

**Comment by nblumhardt** [comment]
Thanks for the heads-up! The sample's missing an indication that some imports are needed:

```java
import static serilogj.sinks.coloredconsole.ColoredConsoleSinkConfigurator.*;
import static serilogj.sinks.rollingfile.RollingFileSinkConfigurator.*;
import static serilogj.sinks.seq.SeqSinkConfigurator.*;
```

I've added them now.

**Comment by mjnorman** [comment]
Ah I see, Eclipse wouldn't detect the static methods.

If I want to have this enable off of a levelswitch such as in my example above, do I have to do it the way I was doing it instead of using the static method?

**Comment by mjnorman** [comment]
@nblumhardt wasn't sure if you get notified of closed issue comments, but wanted to clarify on the level switch.

**Comment by nblumhardt** [comment]
Hi @mjnorman - yes, it looks like that's the case. The set of parameters accepted by `seq()` seems quite limited, currently:

https://github.com/serilogj/serilogj/blob/master/src/serilogj/sinks/seq/SeqSinkConfigurator.java#L7
