### ISSUE TITLE
Have serilogj write to a different logging output

### ISSUE THREAD

**Issue by mjnorman** [serilogj/serilogj#21]
We have a third party set of libraries from Avaya that are used for call routing etc.  It comes with it's own implementation of logging classes used for writing out to log files.  The way we access these is as such:

```
public class MyCallListener extends CallListenerAbstract 
{
    private static Logger logger = Logger.getLogger(MyCallListener.class);
...
   logger.fine("Hello from logging.");
```

I would like to be able to supplement this by using serilogj to write out to SEQ as we have done in the past.  Is there a way to have serilogj write out to this other library as well as to SEQ?  Or am I destined to have to write two log messages everytime I want to log something, so that it still shows up in the proprietary logs as well as output to SEQ?

```
logger.fine("Hello from logging.");    //write to standard log files
Log.fine("Hello from logging.");         //write to serilogj -> seq
```

**Comment by nblumhardt** [comment]
Hi @mjnorman - plugging in a custom `ILogEventSink` - https://github.com/serilogj/serilogj/blob/master/src/serilogj/core/ILogEventSink.java - should work in this case, where the sink will emit events to the proprietary logging API.

This would be plugged in using `writeTo(new AvayaLoggingSink())`.

Does this help?

**Comment by mjnorman** [comment]
Thanks for the feedback, I'll go this route.
