### ISSUE TITLE
How to consume this project as package in maven or gradle

### ISSUE THREAD

**Issue by kfstorm** [serilogj/serilogj#9]
Seems I can't find a package named "serilogj" in maven repository. How can I use this project without syncing the source code?

**Comment by nblumhardt** [comment]
@kfstorm I believe JitPack https://jitpack.io/ enables this.

@80dB would it make sense to publish this on Maven Central and/or JCenter? If you would like a hand with it please just give the word! :-) Cheers!

**Comment by 80dB** [comment]
It does make sense to publish this on Maven, but I have no idea what is required to do so, or if there are specific standards that we need to comply to (like namespaces). 

There are video instructions about it:
http://central.sonatype.org/pages/producers.html

But with the current work load at the office it'll be hard for me to accomplish this. Java isn't our 'main language', we only use it because it's required for Wowza. And we added it to our private-maven repository.

**Comment by nblumhardt** [comment]
@80dB I'm happy to dig into it, if you're open to some extra help on the project? I think the first question will be whether to spin up an organisation (a `serilogj` GitHub org?) so that the packages can live under a community identity, or if you are keen to create an individual account to publish under. I can spare some bandwidth to help with maintenance etc. if it would work for you/your org. Cheers!

**Comment by 80dB** [comment]
@nblumhardt I would think a community identity. The code was written entirely based on your Serilog :)

**Comment by nblumhardt** [comment]
:+1: shall we create a `serilogj` GitHub organization?

**Comment by 80dB** [comment]
Ok, think I've got this covered ;)

I invited you as owner of this organization and transfered the repo to this organisation.

**Comment by nblumhardt** [comment]
Fantastic; I'm there! 👍 

Will be patchy time available, but should be able to dig in over the next few weeks. Thanks!!!

**Comment by nblumhardt** [comment]
@80dB planning to set up CI with _AppVeyor_ and use https://www.appveyor.com/docs/deployment/bintray/ to publish to bintray/jcenter, let me know if I'm off track :-)

@kfstorm is bintray/jcenter a good option for you? Thanks!

**Comment by nblumhardt** [comment]
I apologize in advance for any obvious shortcomings, I've never published artifacts on Bintray before. I'll PR the packaging changes I made shortly.

The package is at: https://bintray.com/serilogj/serilogj/serilogj

I've also submitted it for inclusion in JCenter (can take several hours apparently).

The package was published by hand using `mvn deploy` , next step is to get CI running.

**Comment by nblumhardt** [comment]
From Bintray support:

> JCenter hosts java applications that follow maven convention. In addition to the .pom and .jar files, your version should include a sources jar, and optionally a javadoc jar.
> Your files should be under a maven path layout. (See https://bintray.com/docs/usermanual/uploads/uploads_includingyourpackagesinjcenter.html)
> Once those files are added, we'll be glad to include your package in JCenter.

Will need to spend some time figuring out how to do this.

**Comment by kfstorm** [comment]
WOW, you guys are awesome! I really like Serilog and can’t find a replacement in Java world. It’ll be great if you can publish serilogj as package. Thank you for your efforts! @nblumhardt bintray/jcenter is great.

**Comment by nblumhardt** [comment]
Great, thanks for the feedback @kfstorm :-)

https://bintray.com/bintray/jcenter?filterByPkgName=serilogj

Let us know if you have any difficulties consuming it.

**Comment by arisliang** [comment]
Still how to import this in maven? I try to include this as maven dependency

<dependency>
  <groupId>org.serilogj.serilogj</groupId>
  <artifactId>serilogj</artifactId>
  <version>0.5.1</version>
  <type>pom</type>
</dependency>

But Intellij says cannot find the package.

**Comment by 80dB** [comment]
To use it in maven read:
https://bintray.com/docs/usermanual/formats/formats_mavenrepositories.html

**Comment by minhaz1217** [comment]
> @kfstorm I believe JitPack https://jitpack.io/ enables this.
> 
> @80dB would it make sense to publish this on Maven Central and/or JCenter? If you would like a hand with it please just give the word! :-) Cheers!

Thanks it works.
For anyone finding this thread on how to add serilogj in gradle here is a sample that worked for me
```
repositories {
    ...   
    maven { url 'https://jitpack.io' }
}

dependencies {
    ...
    implementation 'com.github.serilogj:serilogj:v0.6.1'
}
```
